### ISSUE TITLE
添加C#绑定支持

### ISSUE THREAD

**Issue by ZerxZ** [GodotHub/Gype#1]
gde生成c#绑定库
https://github.com/Delsin-Yu/CSharp-Wrapper-Generator-for-GDExtension
判断引擎内置类型(4.4 dev3 以上支持):
https://github.com/godotengine/godot/pull/90703#issuecomment-2358978807

**Comment by moluopro** [comment]
不清楚这条issue的意图是什么，您可以详细说明一下

**Comment by moluopro** [comment]
看起来是打广告的，拉黑了。
